services:
  db:
    image: mysql:8.3
    container_name: beekeeper_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: beekeeper_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
      # Initialize the database with our schema
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      # Expose MySQL on localhost:3306
      - "3306:3306"


volumes:
  db_data:
