services:
  db:
    image: mysql:8.3
    container_name: beekeeper_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: beekeeper_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  api:
    profiles: ["production"]
    build: .
    container_name: beekeeper_api
    restart: always
    ports:
      - "3000:3000"  # Maps host:container
    environment:
      DATABASE_URL: mysql://admin:root@db:3306/beekeeper_db
    depends_on:
      - db

volumes:
  db_data:
